language: objective-c
matrix:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode8
install:
  - gem install cocoapods --pre
before_script:
  - rm -rf ~/Library/Developer/Xcode/DerivedData
  - pod setup
script:
  - pod install
  - pod lib lint
  - carthage update
  - xcodebuild -scheme 'BMSAnalytics iOS' clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - xcodebuild -scheme 'BMSAnalytics watchOS' clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - xcodebuild test -scheme 'BMSAnalytics Tests' -destination 'platform=iOS Simulator,name=iPhone 6s'